import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex justify-center gap-6 border-b border-black/8 py-3 text-sm font-medium dark:border-white/[.145]">
          <Link href="/" className="text-black hover:underline dark:text-zinc-50">
            Todos
          </Link>
          <Link href="/chat" className="text-black hover:underline dark:text-zinc-50">
            Agent Chat
          </Link>
          <Link href="/logs" className="text-black hover:underline dark:text-zinc-50">
            Logs
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
